const KEY="moneyTrackerV1";
const ACCOUNTS_KEY="moneyTrackerAccountsV1";
let transactions=JSON.parse(localStorage.getItem(KEY)||"[]");
let accounts=JSON.parse(localStorage.getItem(ACCOUNTS_KEY)||"[]");
let statsPeriod="month";
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n||0);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const fmtDate=d=>new Date(d+"T00:00:00").toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});
const fullToday=()=>new Date().toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
const save=()=>localStorage.setItem(KEY,JSON.stringify(transactions));
const saveAccounts=()=>localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(accounts));
const categories={income:["Salary","Freelance","Business","Investment","Gift","Other income"],expense:["Food","Transport","Shopping","Bills","Rent","Health","Education","Entertainment","Travel","Other expense"]};
function escapeHTML(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===id));window.scrollTo({top:0,behavior:"smooth"})}
function currentMonthRange(offset=0){const d=new Date(),first=new Date(d.getFullYear(),d.getMonth()+offset,1),last=new Date(d.getFullYear(),d.getMonth()+offset+1,0);return{start:first,end:last}}
function inRange(t,start,end){const d=new Date(t.date+"T00:00:00");return d>=start&&d<=end}
function totals(list){return list.reduce((a,t)=>{a[t.type]+=Number(t.amount);return a},{income:0,expense:0})}
function accountBalance(id){return transactions.filter(t=>t.accountId===id).reduce((s,t)=>s+(t.type==="income"?Number(t.amount):-Number(t.amount)),0)}
function renderDashboard(){
 const total=totals(transactions),bal=total.income-total.expense,m=currentMonthRange(),mt=totals(transactions.filter(t=>inRange(t,m.start,m.end)));
 $("dashboardDate").textContent=fullToday();$("balance").textContent=money(bal);$("totalIncome").textContent=money(total.income);$("totalExpense").textContent=money(total.expense);$("monthSaving").textContent=money(mt.income-mt.expense);$("balanceStatus").textContent=bal>=0?"You're in positive balance":"Expenses are higher than income";
 renderAccounts();renderCategoryChart();
 const list=transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).slice(0,12);
 $("recentList").innerHTML=list.length?list.map(t=>`<div class="transaction" data-id="${t.id}"><div class="tx-icon">${t.type==="income"?"↗":"↘"}</div><div class="tx-main"><strong>${escapeHTML(t.description)}</strong><span>${escapeHTML(t.category)} · ${fmtDate(t.date)} · ${escapeHTML(accountName(t.accountId))}</span></div><div class="tx-amount ${t.type}">${t.type==="income"?"+":"−"}${money(t.amount)}</div></div>`).join(""):`<div class="empty">No transactions yet.<br>Add your first income or expense above. ✨</div>`;
 document.querySelectorAll(".transaction").forEach(x=>x.onclick=()=>editTransaction(Number(x.dataset.id)));
}
function accountName(id){const a=accounts.find(x=>x.id===id);return a?a.name:"Unassigned"}
function renderAccounts(){
 const total=transactions.reduce((s,t)=>s+(t.type==="income"?Number(t.amount):-Number(t.amount)),0);
 const markup=accounts.length?accounts.map(a=>`<div class="account-card"><div><strong>${escapeHTML(a.name)}</strong><span>${escapeHTML(a.type||"Account")}</span></div><strong class="account-balance ${accountBalance(a.id)<0?"negative":""}">${money(accountBalance(a.id))}</strong></div>`).join("")+`<div class="account-total"><span>All accounts</span><strong>${money(total)}</strong></div>`:`<div class="empty small-empty">No accounts yet. Add one before recording transactions.</div>`;
}
function renderCategoryChart(){
 const [start,end]=periodRange("month"),cats={};transactions.filter(t=>t.type==="expense"&&inRange(t,start,end)).forEach(t=>cats[t.category]=(cats[t.category]||0)+Number(t.amount));
 const rows=Object.entries(cats).sort((a,b)=>b[1]-a[1]),total=rows.reduce((s,x)=>s+x[1],0);
 $("dashboardCategoryBreakdown").innerHTML=rows.length?rows.map(([c,v])=>`<div class="category-row"><div class="cat-top"><span>${escapeHTML(c)}</span><strong>${money(v)} · ${total?Math.round(v/total*100):0}%</strong></div><div class="progress"><i style="width:${total?v/total*100:0}%"></i></div></div>`).join(""):`<div class="empty">No expenses this month.</div>`;
}
function openForm(type,id=null){
 if(!accounts.length){alert("Please add an account first.");showView("accountsView");return}
 $("transactionForm").reset();$("editId").value=id||"";$("type").value=type;$("date").value=today();$("formTitle").textContent=id?"Edit transaction":`Add ${type}`;$("saveBtn").textContent=id?"Update transaction":"Save transaction";$("deleteBtn").classList.toggle("hidden",!id);populateCategories(type);populateAccountSelect();
 if(id){const t=transactions.find(x=>x.id===id);if(t){$("amount").value=t.amount;$("description").value=t.description;$("category").value=t.category;$("date").value=t.date;$("accountId").value=t.accountId||accounts[0].id}}
 showView("formView");$("amount").focus();
}
function populateCategories(type){$("category").innerHTML=categories[type].map(c=>`<option>${c}</option>`).join("")}
function populateAccountSelect(){ $("accountId").innerHTML=accounts.map(a=>`<option value="${a.id}">${escapeHTML(a.name)}</option>`).join("") }
function editTransaction(id){const t=transactions.find(x=>x.id===id);if(t)openForm(t.type,id)}
$("transactionForm").onsubmit=e=>{e.preventDefault();const id=Number($("editId").value),item={id:id||Date.now(),type:$("type").value,amount:Number($("amount").value),description:$("description").value.trim(),category:$("category").value,date:$("date").value,accountId:Number($("accountId").value)};if(!item.amount||!item.description||!item.date||!item.accountId)return;if(id)transactions=transactions.map(t=>t.id===id?item:t);else transactions.push(item);save();renderAll();showView("dashboardView");toast(id?"Transaction updated":"Transaction added")};
$("deleteBtn").onclick=()=>{const id=Number($("editId").value);if(confirm("Delete this transaction?")){transactions=transactions.filter(t=>t.id!==id);save();renderAll();showView("dashboardView");toast("Transaction deleted")}};
$("backBtn").onclick=()=>showView("dashboardView");document.querySelectorAll("[data-open-form]").forEach(b=>b.onclick=()=>openForm(b.dataset.openForm));document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>showView(b.dataset.view));
$("clearAllBtn").onclick=()=>{if(transactions.length&&confirm("Delete all transactions? This cannot be undone.")){transactions=[];save();renderAll();toast("All transactions cleared")}};
document.querySelectorAll("#statsPeriod button").forEach(b=>b.onclick=()=>{statsPeriod=b.dataset.period;document.querySelectorAll("#statsPeriod button").forEach(x=>x.classList.toggle("active",x===b));renderStats()});
function periodRange(p){const now=new Date();if(p==="week"){const d=new Date(now),day=d.getDay(),diff=day===0?-6:1-day,start=new Date(d);start.setDate(d.getDate()+diff);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+6);end.setHours(23,59,59,999);return[start,end]}if(p==="year")return[new Date(now.getFullYear(),0,1),new Date(now.getFullYear(),11,31,23,59,59,999)];return currentMonthRange()}
function renderStats(){
 const [start,end]=periodRange(statsPeriod),t=totals(transactions.filter(x=>inRange(x,start,end))),net=t.income-t.expense,rate=t.income?net/t.income*100:0;$("statIncome").textContent=money(t.income);$("statExpense").textContent=money(t.expense);$("statNet").textContent=money(net);$("statRate").textContent=`${Math.round(rate)}%`;
 const max=Math.max(t.income,t.expense,1);$("barChart").innerHTML=`<div class="bar-wrap"><strong class="bar-value">${money(t.income)}</strong><div class="bar income" style="height:${Math.max(4,t.income/max*125)}px"></div><span class="bar-label">Income</span></div><div class="bar-wrap"><strong class="bar-value">${money(t.expense)}</strong><div class="bar expense" style="height:${Math.max(4,t.expense/max*125)}px"></div><span class="bar-label">Expenses</span></div>`;
 const expenses=transactions.filter(x=>x.type==="expense"&&inRange(x,start,end)),cats={};expenses.forEach(x=>cats[x.category]=(cats[x.category]||0)+Number(x.amount));const rows=Object.entries(cats).sort((a,b)=>b[1]-a[1]),total=rows.reduce((s,x)=>s+x[1],0);$("categoryBreakdown").innerHTML=rows.length?rows.map(([c,v])=>`<div class="category-row"><div class="cat-top"><span>${escapeHTML(c)}</span><strong>${money(v)}</strong></div><div class="progress"><i style="width:${total?v/total*100:0}%"></i></div></div>`).join(""):`<div class="empty">No expenses in this period.</div>`;
}
function monthTotals(offset){const r=currentMonthRange(offset);return totals(transactions.filter(t=>inRange(t,r.start,r.end)))}function monthName(offset){const d=new Date();d.setMonth(d.getMonth()+offset);return d.toLocaleDateString("en-IN",{month:"long",year:"numeric"})}function change(current,prev){return prev===0?(current===0?0:100):((current-prev)/prev)*100}
function renderCompare(){const c=monthTotals(0),p=monthTotals(-1);$("compareLabel").textContent=`${monthName(0)}  vs  ${monthName(-1)}`;const rows=[["Income",c.income,p.income],["Expenses",c.expense,p.expense],["Net savings",c.income-c.expense,p.income-p.expense]];$("comparisonList").innerHTML=rows.map(([name,cur,prev])=>{const pct=change(cur,prev),cls=pct>0?"up":pct<0?"down":"";return `<div class="compare-card"><div class="compare-title">${name}</div><div class="compare-values"><div><small>Current</small><strong>${money(cur)}</strong></div><div><small>Previous</small><strong>${money(prev)}</strong></div><div><small>Change</small><strong class="${cls}">${pct===0?"0%":`${pct>0?"+":""}${Math.round(pct)}%`}</strong></div></div></div>`}).join("");let insight="";if(c.expense>p.expense)insight+=`Your expenses are ${money(c.expense-p.expense)} higher than last month. `;else if(c.expense<p.expense)insight+=`Nice! Your expenses are ${money(p.expense-c.expense)} lower than last month. `;if(c.income>p.income)insight+=`Income increased by ${money(c.income-p.income)}.`;else if(c.income<p.income)insight+=`Income decreased by ${money(p.income-c.income)}.`;if(!insight)insight="Your income and expenses are unchanged compared with last month.";$("comparisonInsight").textContent=insight}
function renderAll(){renderDashboard();renderStats();renderCompare();}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2200)}
$("themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("moneyTheme",document.body.classList.contains("dark")?"dark":"light");$("themeBtn").textContent=document.body.classList.contains("dark")?"☀":"☾"};if(localStorage.getItem("moneyTheme")==="dark"){document.body.classList.add("dark");$("themeBtn").textContent="☀"}
function addAccount(){const name=$("newAccountName").value.trim(),type=$("newAccountType").value;if(!name){toast("Enter an account name");return}accounts.push({id:Date.now(),name,type});saveAccounts();$("newAccountName").value="";renderAccounts();populateAccountSelect();toast("Account added")}
$("addAccountBtn").onclick=addAccount;$("newAccountName").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();addAccount()}};
function reportRows(){return transactions.slice().sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id).map(t=>({Date:t.date,Type:t.type==="income"?"Income":"Expense",Account:accountName(t.accountId),Category:t.category,Description:t.description,Amount:Number(t.amount),Signed_Amount:t.type==="income"?Number(t.amount):-Number(t.amount)}))}
function reportTotals(){const t=totals(transactions);return{income:t.income,expense:t.expense,net:t.income-t.expense}}
function downloadBlob(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportExcel(){if(!transactions.length){toast("No transactions to export");return}if(typeof XLSX==="undefined"){toast("Excel library could not load");return}const rows=reportRows(),t=reportTotals(),summary=[["MY MONEY TRACKER REPORT"],[],["Generated",new Date().toLocaleString("en-IN")],["Total Income",t.income],["Total Expenses",t.expense],["Net Savings",t.net],[],["Date","Type","Account","Category","Description","Amount","Signed Amount"],...rows.map(r=>[r.Date,r.Type,r.Account,r.Category,r.Description,r.Amount,r.Signed_Amount])];const ws=XLSX.utils.aoa_to_sheet(summary);ws["!cols"]=[{wch:13},{wch:12},{wch:20},{wch:18},{wch:34},{wch:15},{wch:16}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Transactions");const cat={};transactions.filter(x=>x.type==="expense").forEach(x=>cat[x.category]=(cat[x.category]||0)+Number(x.amount));const catRows=[["Category","Expenses"],...Object.entries(cat).sort((a,b)=>b[1]-a[1])];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(catRows),"Expense Breakdown");const accRows=[["Account","Balance"],...accounts.map(a=>[a.name,accountBalance(a.id)])];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(accRows),"Accounts");XLSX.writeFile(wb,`money-report-${today()}.xlsx`);toast("Excel saved to your Downloads")}
function exportPdf(){if(!transactions.length){toast("No transactions to export");return}if(!window.jspdf){toast("PDF library could not load");return}const{jsPDF}=window.jspdf,doc=new jsPDF({unit:"mm",format:"a4"}),t=reportTotals();let y=18;doc.setFontSize(18);doc.text("My Money Tracker",14,y);y+=8;doc.setFontSize(10);doc.text(`Financial report • ${new Date().toLocaleDateString("en-IN")}`,14,y);y+=10;doc.setFontSize(11);doc.text(`Total Income: ${money(t.income)}`,14,y);doc.text(`Total Expenses: ${money(t.expense)}`,80,y);doc.text(`Net Savings: ${money(t.net)}`,150,y);y+=10;doc.setFontSize(9);doc.text("Date",14,y);doc.text("Type",32,y);doc.text("Account",49,y);doc.text("Category",83,y);doc.text("Description",120,y);doc.text("Amount",177,y);y+=5;doc.line(14,y-2,196,y-2);reportRows().forEach(r=>{if(y>282){doc.addPage();y=18;doc.setFontSize(9);doc.text("Date",14,y);doc.text("Type",32,y);doc.text("Account",49,y);doc.text("Category",83,y);doc.text("Description",120,y);doc.text("Amount",177,y);y+=6}const desc=r.Description.length>24?r.Description.slice(0,21)+"...":r.Description;doc.text(r.Date,14,y);doc.text(r.Type,32,y);doc.text(r.Account.slice(0,16),49,y);doc.text(r.Category.slice(0,16),83,y);doc.text(desc,120,y);doc.text(money(r.Amount),177,y);y+=5});doc.save(`money-report-${today()}.pdf`);toast("PDF saved to your Downloads")}
$("exportExcel").onclick=exportExcel;$("exportPdf").onclick=exportPdf;
if(!Array.isArray(accounts))accounts=[];
if(!accounts.length&&transactions.some(t=>!t.accountId)){const a={id:Date.now(),name:"Main Account",type:"Bank"};accounts=[a];transactions=transactions.map(t=>({...t,accountId:t.accountId||a.id}));saveAccounts();save()}
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});renderAll();
